services:
  - type: web
    name: gotchai-backend
    env: docker
    region: ohio
    plan: free
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: GROQ_API_KEY
        sync: false
      - key: OPIK_API_KEY
        sync: false
      - key: OPIK_WORKSPACE
        value: klepi21
